Django/capstone/capstone/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('policy/', include('policy.urls')),
    path('docs/', include('docs.urls')),
    path('support/', include('support.urls')),
    path('admin/', admin.site.urls)
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/capstone/docs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

Django/capstone/policy/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

Django/capstone/support/urls.py
from django.urls import path
from . import views


app_name = 'support'
urlpatterns = [
    path('', views.index, name='index'),
    path('checkin/', views.checkin, name="checkin"),
    path('request/', views.response, name='request'),
    path('datatable/', views.datatable, name='datatable'),
    path('response/<int:id>/', views.response, name="response"),
] 

Django/capstone/docs/models.py
from django.db import models

# Create your models here.

Django/capstone/policy/models.py
from django.db import models

# Create your models here.

Django/capstone/support/models.py
from django.db import models

# Create your models here.

def user_directory_path(instance, filename): 
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename> 
    return '{0}_{1}'.format(instance.id, filename) 

class SupportType(models.Model):
    support_type = models.CharField(max_length=32)

    def __str__(self):
        return f"ID:{self.id} Type:{self.support_type}"

class Support(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    email = models.EmailField(max_length=128)
    title = models.CharField(max_length=128)
    message = models.TextField(max_length=1024)
    image = models.ImageField(upload_to=user_directory_path, blank=True)
    iphone = models.CharField(max_length=48)
    ios = models.CharField(max_length=16)
    prior_support_id = models.IntegerField(blank=True, null=True)
    response = models.ForeignKey(SupportType, on_delete=models.CASCADE, related_name="support", blank=True, null=True)
    responsed_too = models.BooleanField(default=False)
    def __str__(self):
        return f"ID:{self.id} Title:{self.title[:25]} Prior Support ID:{self.prior_support_id} "

Django/capstone/docs/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    return HttpResponse("Hello, world. You're at the Docs-App index.")

Django/capstone/policy/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    return HttpResponse("Hello, world. You're at the Policy-App index.")

Django/capstone/support/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls.base import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render
from django.http import HttpResponse
from .models import Support, SupportType
from django.core.mail import send_mail
from django.conf import settings
# Create your views here.

def index(request):
    print("Got here!")
    if request.method == "POST":
        support = Support()
        form = request.POST
        support.title = form['title']
        support.email = form['email']
        support.message = form['message']
        support.image = request.FILES.get('image', '')
        support.iphone = form['iphone']
        support.ios = form['ios']

        priors = Support.objects.filter(email=support.email)
        last_id = 0
        for prior in priors:
            print(f"Prior email: {last_id}")
            if prior.id > last_id and prior.response.support_type == "support":
                last_id = prior.id 
                print(f"Last: {last_id}")

        obj, created = SupportType.objects.get_or_create(support_type='support')
        obj.save()

        support.response = obj
        support.prior_support_id=last_id
        support.save()

        print("Success Posting")
        
        return HttpResponseRedirect(reverse('support:index'))  # TODO: Need to redirect to another page and tell them we'll get back them as soon as possible
    return render(request, 'support/index.html')
    #print("No POST")
    #return HttpResponse("Hello, world. You're at the Support-App index.")

def request(request):
    if request.user.is_authenticated:
        print("Success authenticated")
        support = Support.objects.all()

        context = {
            "support": support,
        }
        return render(request, 'support/response.html', context)
    print("Failure NOT authenticated")
    return render(request, 'support/index.html')


def response(request, id):
    print("Got here!")
    if request.user.is_authenticated:
        print("Athenticated")
        if request.method == "POST":
            print("Made a POST")
            support = Support.objects.get(id=id)
            form = request.POST
            msg = form['message']
            title = 'RE:>' + support.title
            print("Success Posting")
            success = send_mail(
                title,
                msg,
                settings.SUPPORT_EMAIL,
                [support.email],
                fail_silently=False,
            )
            if success:
                support.responsed_too = True
                support.save()
                support = Support.objects.all()
                context = {
                    "support": support,
                }
                return render(request, 'support/datatable.html', context)
        else:
            # TODO: Need to fill out a single page details via context
            print("None POST action")
            support = Support.objects.get(id=id)
            print(support)
            context = {
                "support": support,
            }
            return render(request, 'support/response.html', context)
    print("Why didn't we athenticate???")
    return render(request, 'support/index.html')


def datatable(request):
    print("got to datatable")
    if request.user.is_authenticated:
        print("Success authenticated")
        support = Support.objects.all()
        context = {
            "support": support,
        }
        return render(request, 'support/datatable.html', context)
    return render(request, 'support/index.html')



def checkin(request):
    if request.method == "POST":
        form = request.POST
        username = form['username']
        password = form['password']
        user = authenticate(request, username=username, password=password)
        print(username, password, user)
        if user is not None:
            print('logging in user')
            login(request, user)
            return HttpResponseRedirect(reverse('support:datatable'))
    return render(request, 'support/checkin.html')



# def user_login(request):
#     if request.method == "GET":
#         error = request.GET.get('error', '')
#         context = {
#             'error': error
#         }
#         return render(request, 'support/login.html', context)
#     elif request.method == "POST":
#         username = request.POST['username']
#         password = request.POST['password']

#         user = authenticate(request, username=username, password=password)
#         print("Who's the user", user)
#         if user is not None:
#             login(request, user)
#             # Redirect to success...
#             print("Redirect to success...")
#             print("Success authenticated")
#             return render(request, 'support/response.html')
#         else:
#             print("Error or here?")
#             return HttpResponseRedirect(reverse('support:login') + '?error=Username or Password is incorrect.')
#     print("Neither POST or GET")
#     return render(request, 'support/index.html')

Django/capstone/support/templates/support/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>

<body>
    {% block content %}{% endblock %}       

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
</body>

</html>

Django/capstone/support/templates/support/base_table.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!-- Datatables CSS -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/select/1.3.3/css/select.dataTables.min.css">
    

    <!-- jQuery JS -->
    <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <!-- DataTables JS -->
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/select/1.3.3/js/dataTables.select.min.js"></script>
    
    <script type="text/javascript" class="init">
    /*$(document).ready(function() {
        $('#example').DataTable( {
            columnDefs: [ {
                orderable: false,
                className: 'select-checkbox',
                targets:   0
            } ],
            select: {
                style:    'os',
                selector: 'td:first-child'
            },
            order: [[ 1, 'asc' ]]
        } );

        var table = $('#example').DataTable();
        table.on( 'select', function ( e, dt, type, indexes ) {
            if ( type === 'row' ) {
                var data = table.rows( indexes ).data()
                window.location.href = '/support/response/' + data[0][1];
            }
        } );
    } );*/

    $(document).ready(function() {
        var table = $('#example').DataTable();
    
        $('#example tbody').on( 'click', 'tr', function () {
            if ( $(this).hasClass('selected') ) {
                $(this).removeClass('selected');
            }
            else {
                table.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');
            }
        } );
    
        $('#button').click( function () {
            data = table.row('.selected').data();
            window.location.href = '/support/response/' + data[1];
        } );
    } );


    </script>
</head>

<body>
    {% block content %}{% endblock %}       

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
</body>

</html>

Django/capstone/support/templates/support/checkin.html
{% extends "support/base.html" %}

{% load static %}

{% block header %}<title>Checkin - Support</title>{% endblock %}

{% block content %}
    <div class="container">
    <nav class="mt-3 mb-3" aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'support:index' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Login</li>
      </ol>
    </nav>
        {% if error %}
        {{error}}
        {% endif %}
        <form action="{% url 'support:checkin' %}" method="post" class="needs-validation" novalidate="">
            {% csrf_token %}
          <div class="row g-3">
            <div class="col-sm-6 mt-3 mb-3">
              <label for="username" class="form-label">Username</label>
              <input type="text" class="form-control" id="username" name="username" placeholder="Username" value="{{username}}">
              <div class="invalid-feedback">
                Valid 'Username' name is required.
              </div>
            </div>

            <div class="col-sm-6 mt-3 mb-3">
              <label for="password" class="form-label">Password</label>
              <input type="password" class="form-control" id="password" name="password" placeholder="Password" value="" required="">
              <div class="invalid-feedback">
                Valid 'Password' name is required.
              </div>
            </div>
          </div>
        <button class="w-100 btn btn-primary btn-lg" type="submit">Login In</button>
      </form>
    </div>
{% endblock %}

Django/capstone/support/templates/support/datatable.html
{% extends "support/base_table.html" %}

{% load static %}

{% block header %}<title>Requests for Support Emails Dashboard</title>{% endblock %}

{% block content %}

<div class="container">

  <nav aria-label="breadcrumb" class="mt-3 mb-3">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Data Tables</li>
    </ol>
  </nav>
  <button id="button" class="w-100 btn btn-primary btn-lg mt-3 mb-3" type="submit">Response To</button>
  <table id="example" class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Responsed To</th>
                <th>ID</th>
                <th>Email</th>
                <th>Title</th>
                <th>Message</th>
                <th>iPhone</th>
                <th>iOS</th>
                <th>Image</th>
                <th>Prev ID</th>
                <th>Type</th>
            </tr>
        </thead>
        <tbody>
            {% for sup in support %}
            <tr>
                {% if sup.responsed_too is True %}
                <td> Yes </td>
                {% else %}
                <td>   </td>
                {% endif %}
                <td>{{sup.id}}</td>
                <td>{{sup.email}}</td>
                <td>{{sup.title}}</td>
                <td>{{sup.message}}</td>
                <td>{{sup.iphone}}</td>
                <td>{{sup.ios}}</td>
                <td>{{sup.image}}</td>
                {% if sup.prior_support_id is None %}
                  <td></td>
                {% else %}
                  <td>{{sup.prior_support_id}}</td>
                {% endif %}
                <td>{{sup.response.support_type}}</td>   
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <th>Responsed To</th>
                <th>ID</th>
                <th>Email</th>
                <th>Title</th>
                <th>Message</th>
                <th>iPhone</th>
                <th>iOS</th>
                <th>Image</th>
                <th>Prev ID</th>
                <th>Type</th>
            </tr>
        </tfoot>
    </table>
</div>
{% endblock %}

Django/capstone/support/templates/support/index.html
{% extends "support/base.html" %}

{% load static %}

{% block header %}{% endblock %}

{% block content %}
    <div class="container">
        <nav class="mt-3 mb-3" aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Support</li>
          </ol>
        </nav>

        <div class="mt-4 mb-1">
          <h1>Request Support</h1>
        </div>

        <form action="{% url 'support:index' %}" method="post" class="needs-validation" novalidate="" enctype="multipart/form-data">
            {% csrf_token %}
          <div class="row g-3">
            <div class="col-sm-6 mt-5 mb-1">
              <label for="title" class="form-label">Title</label>
              <input type="text" class="form-control" id="title" name="title" placeholder="Title..." required>
              <div class="invalid-feedback">
                Provide a breif description for title.
              </div>
            </div>
            <div class="col-sm-6 mt-5 mb-1">
              <label for="email" class="form-label">Email</label>
              <input type="email" class="form-control" id="email" name="email" placeholder="your@email.com" required>
              <div class="invalid-feedback">
                Provide your email for support.
              </div>
            </div>
          </div>

        <div class="row g-3">
            <div class="col-sm-6 mt-4 mb-1">
              <label for="iphone" class="form-label">iPhone Model</label>
              <input type="text" class="form-control" id="iphone" name="iphone" placeholder="Model..." required>
              <div class="invalid-feedback">
                Provide iPhone model for support.
              </div>
            </div>
            <div class="col-sm-6 mt-4 mb-1">
              <label for="ios" class="form-label">iOS</label>
              <input type="text" class="form-control" id="ios" name="ios" placeholder="Version..." required>
              <div class="invalid-feedback">
                Provide your iOS version for support.
              </div>
            </div>
          </div>

        
        <div class="form-group mt-4 mb-1">
          <label for="message">Explanation of issue</label>
          <textarea class="form-control" id="message" rows="6" name="message" placeholder="Issue description..." required></textarea>
        </div>
        <button class="w-100 btn btn-primary btn-lg mt-3 mb-3" type="submit">Login In</button>
    </div>
{% endblock %}

Django/capstone/support/templates/support/request.html
{% extends "support/base.html" %}

{% load static %}

{% block header %}<title>Reponse Dashboard</title>{% endblock %}

{% block content %}
    <div class="container">

        <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Response</li>
        </ol>
        </nav>

        <h1>Support Requests</h1>
        {% for sup in support %}
            {% if forloop.first %}
                <div data="{{forloop.counter}}" class="row mb-2">
            {% elif forloop.counter0|divisibleby:2 %}
                </div>
                <div data="{{forloop.counter}}" class="row mb-2">
            {% endif %}

                <div class="col-md-6">
                <div class="card flex-md-row mb-4 box-shadow h-md-250">
                    <div class="card-body d-flex flex-column align-items-start">
                    <strong class="d-inline-block mb-2 text-primary">{{ sup.id }}</strong>
                    <h3 class="mb-0">
                        <a class="text-dark" href="#">{{sup.email.capitalize}}</a>
                    </h3>
                    <div class="mb-1 text-muted">
                        <ul class="list-unstyled">
                            <li>{{sup.response.support_type}}</li>
                            <li>{{sup.title}}</li>
                            <li>{{sup.iphone}}</li>
                            <li>{{sup.ios}}</li>
                            <li>{{sup.prior_support_id}}</li>
                            <li>{{sup.message}}</li>
                        </ul>
                    </div>
                    <a href="#">Additonal Details</a>
                    </div>
                    {% if sup.image %}
                    <img class="card-img-right flex-auto d-none d-md-block" src={{sup.image.url}} alt="Thumbnail [200x250]" style="width: 150px; height: 200px;" data-holder-rendered="true">
                    {% endif %}
                </div>
                </div>
            {% if forloop.last %}
                </div>
            {% endif %}
        {% endfor %}

    </div>
{% endblock %}

Django/capstone/support/templates/support/response.html
{% extends "support/base.html" %}

{% load static %}

{% block header %}<title>Support - Index</title>{% endblock %}

{% block content %}
        <div class="container">
        <nav aria-label="breadcrumb" class="mt-3 mb-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'support:datatable' %}">DataTable</a></li>
            <li class="breadcrumb-item active" aria-current="page">Response</li>
        </ol>
        </nav>

        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-primary">{{support.email}}</strong>
                <div class="mb-1 text-muted">Title:</div>
                <h3 class="mb-0">{{support.title}}</h3>
                <div class="mb-1 text-muted">Date</div>
                <p class="card-text mb-auto">{{support.date_created}}</p>
                <div class="mb-1 text-muted">Message:</div>
                <p class="card-text mb-auto">{{support.message}}</p>
                <div class="mb-1 text-muted">Phone:</div>
                <p class="card-text mb-auto">{{support.iphone}}</p>
                <div class="mb-1 text-muted">iOS:</div>
                <p class="card-text mb-auto">{{support.ios}}</p>
            </div>
            {% if support.image|length > 0 %}
                <div class="col-auto d-none d-lg-block">
                    <img class="card-img-right flex-auto d-none d-md-block" src={{support.image.url}} alt="Thumbnail [200x250]" style="width: 150px; height: 200px;" data-holder-rendered="true">
                </div>
            {% endif %}
        </div>

        <form action="{% url 'support:response' support.id  %}" method="POST">
            {% csrf_token %}
            <div class="form-group mt-4 mb-1">
            <label for="message">Explanation of issue</label>
            <textarea class="form-control" id="message" rows="10" name="message" placeholder="Support description..." required></textarea>
            </div>
            <button id="button" class="w-100 btn btn-primary btn-lg mt-3 mb-3" type="submit">Response To</button>
        </form>
    </div>
{% endblock %}